if IsInToolsMode() then
    LOADING_TIME = 2
    PRE_ROUND_TIME = 5
    ROUND_TIME = 70
    POST_ROUND_TIME = 15
else
    LOADING_TIME = 2
    PRE_ROUND_TIME = 30
    ROUND_TIME = 4 * 60
    POST_ROUND_TIME = 20
end